/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/agent/workbench/v2/conversations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Conversations */
    get: operations["list_conversations_api_agent_workbench_v2_conversations_get"];
    put?: never;
    /** Create Conversation */
    post: operations["create_conversation_api_agent_workbench_v2_conversations_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/agent/workbench/v2/conversations/{conversation_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Conversation */
    get: operations["get_conversation_api_agent_workbench_v2_conversations__conversation_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/agent/workbench/v2/conversations/{conversation_id}/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Events */
    get: operations["list_events_api_agent_workbench_v2_conversations__conversation_id__events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/agent/workbench/v2/conversations/{conversation_id}/candidates/{candidate_id}/detail": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Candidate Detail */
    get: operations["get_candidate_detail_api_agent_workbench_v2_conversations__conversation_id__candidates__candidate_id__detail_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/agent/workbench/v2/conversations/{conversation_id}/messages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit Message */
    post: operations["submit_message_api_agent_workbench_v2_conversations__conversation_id__messages_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/agent/workbench/v2/conversations/{conversation_id}/requirement-actions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Apply Requirement Action */
    post: operations["apply_requirement_action_api_agent_workbench_v2_conversations__conversation_id__requirement_actions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/agent/workbench/v2/conversations/{conversation_id}/runtime/recheck": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Recheck And Continue */
    post: operations["recheck_and_continue_api_agent_workbench_v2_conversations__conversation_id__runtime_recheck_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/liepin/compliance-gates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Compliance Gate */
    post: operations["create_compliance_gate_api_liepin_compliance_gates_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/liepin/compliance-gates/{gate_ref}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Compliance Gate */
    get: operations["get_compliance_gate_api_liepin_compliance_gates__gate_ref__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/liepin/compliance-gates/{gate_ref}/bind-account": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Bind Compliance Gate Account */
    post: operations["bind_compliance_gate_account_api_liepin_compliance_gates__gate_ref__bind_account_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/liepin/compliance-gates/{gate_ref}/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify Compliance Gate */
    post: operations["verify_compliance_gate_api_liepin_compliance_gates__gate_ref__verify_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/liepin/connections": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Connection */
    post: operations["create_connection_api_liepin_connections_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/liepin/connections/{connection_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Connection */
    get: operations["get_connection_api_liepin_connections__connection_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/liepin/connections/{connection_id}/login-url": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Get Login Url */
    post: operations["get_login_url_api_liepin_connections__connection_id__login_url_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/liepin/connections/{connection_id}/stream-token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Connection Stream Token */
    post: operations["create_connection_stream_token_api_liepin_connections__connection_id__stream_token_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/liepin/connections/{connection_id}/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Stream Connection Events */
    get: operations["stream_connection_events_api_liepin_connections__connection_id__events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** LiepinComplianceGateActionResponse */
    LiepinComplianceGateActionResponse: {
      /** Gateref */
      gateRef: string;
      /**
       * Status
       * @enum {string}
       */
      status: "pending_account_binding" | "approved" | "denied" | "expired";
    };
    /** LiepinComplianceGateConnectionRequest */
    LiepinComplianceGateConnectionRequest: {
      /** Connectionid */
      connectionId: string;
    };
    /** LiepinComplianceGateCreateRequest */
    LiepinComplianceGateCreateRequest: {
      /** Candidatepersonalinfoprocessingbasis */
      candidatePersonalInfoProcessingBasis: string;
      /** Personalinformationprocessor */
      personalInformationProcessor: string;
      /** Operatorauditowner */
      operatorAuditOwner: string;
      /** Accountholderauthorized */
      accountHolderAuthorized: boolean;
      /** Humaninitiatedrecruiting */
      humanInitiatedRecruiting: boolean;
      /** Allowedpurposes */
      allowedPurposes: string[];
      /**
       * Retentionpolicy
       * @enum {string}
       */
      retentionPolicy:
        | "run_debug_short"
        | "workspace_recruiting_record"
        | "forbidden_persist";
      /** Deletionsladays */
      deletionSlaDays: number;
      /** Deletionpath */
      deletionPath: string;
      /**
       * Rawpayloadaccessscope
       * @enum {string}
       */
      rawPayloadAccessScope: "run_only" | "workspace" | "admin_only";
      /** Rawdetailretentionallowedafterdebug */
      rawDetailRetentionAllowedAfterDebug: boolean;
      /** Fixtureexportallowed */
      fixtureExportAllowed: boolean;
      /** Policyref */
      policyRef: string;
    };
    /** LiepinComplianceGateResponse */
    LiepinComplianceGateResponse: {
      /** Gateref */
      gateRef: string;
      /** Tenantid */
      tenantId: string;
      /** Workspaceid */
      workspaceId: string;
      /** Actorid */
      actorId: string;
      /**
       * Status
       * @enum {string}
       */
      status: "pending_account_binding" | "approved" | "denied" | "expired";
      /** Allowedpurposes */
      allowedPurposes: string[];
      /**
       * Retentionpolicy
       * @enum {string}
       */
      retentionPolicy:
        | "run_debug_short"
        | "workspace_recruiting_record"
        | "forbidden_persist";
      /** Policyref */
      policyRef: string;
    };
    /** LiepinConnectionCreateRequest */
    LiepinConnectionCreateRequest: {
      /** Compliancegateref */
      complianceGateRef: string;
    };
    /** LiepinConnectionResponse */
    LiepinConnectionResponse: {
      /** Connectionid */
      connectionId: string;
      /** Tenantid */
      tenantId: string;
      /** Workspaceid */
      workspaceId: string;
      /** Actorid */
      actorId: string;
      /** Compliancegateref */
      complianceGateRef: string;
      /** Status */
      status: string;
    };
    /** LiepinLoginUrlResponse */
    LiepinLoginUrlResponse: {
      /** Connectionid */
      connectionId: string;
      /** Loginurl */
      loginUrl: string;
      /**
       * Handoffstate
       * @constant
       */
      handoffState: "ready_for_browser_login";
    };
    /** ProblemDetails */
    ProblemDetails: {
      /** Type */
      type: string;
      /** Title */
      title: string;
      /** Status */
      status: number;
      /** Detail */
      detail: string;
      /** Reasoncode */
      reasonCode: string;
      /** Instance */
      instance: string;
      /** Correlationid */
      correlationId: string;
      /** Regions */
      regions?: components["schemas"]["ProblemRegion"][];
    };
    /** ProblemRegion */
    ProblemRegion: {
      /** Field */
      field: string;
      /** Message */
      message: string;
      /**
       * Code
       * @default invalid
       */
      code: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** WorkbenchV2CandidateDetailSectionView */
    WorkbenchV2CandidateDetailSectionView: {
      /** Title */
      title: string;
      /** Items */
      items?: string[];
    };
    /** WorkbenchV2CandidateDetailView */
    WorkbenchV2CandidateDetailView: {
      /** Candidateid */
      candidateId: string;
      /** Displayname */
      displayName: string;
      /** Avatarlabel */
      avatarLabel?: string | null;
      /** Avatarcolorkey */
      avatarColorKey?: string | null;
      /** Headline */
      headline?: string | null;
      /** Company */
      company?: string | null;
      /** Currenttitle */
      currentTitle?: string | null;
      /** Currentcompany */
      currentCompany?: string | null;
      /** Location */
      location?: string | null;
      /** City */
      city?: string | null;
      /** Education */
      education?: string | null;
      /** Experienceyears */
      experienceYears?: number | null;
      /** Workyears */
      workYears?: number | null;
      /** Age */
      age?: number | null;
      /** Gender */
      gender?: string | null;
      /** Activestatus */
      activeStatus?: string | null;
      /** Jobstatus */
      jobStatus?: string | null;
      /** Sourcekinds */
      sourceKinds?: ("cts" | "liepin")[];
      /** Sourcelabel */
      sourceLabel?: string | null;
      /** Matchscore */
      matchScore?: number | null;
      match?: components["schemas"]["WorkbenchV2CandidateMatchView"] | null;
      jobIntention?:
        | components["schemas"]["WorkbenchV2CandidateJobIntentionView"]
        | null;
      /** Workexperience */
      workExperience?: components["schemas"]["WorkbenchV2CandidateTimelineItemView"][];
      /** Projectexperience */
      projectExperience?: components["schemas"]["WorkbenchV2CandidateTimelineItemView"][];
      /** Educationexperience */
      educationExperience?: components["schemas"]["WorkbenchV2CandidateTimelineItemView"][];
      /** Skills */
      skills?: string[];
      /** Sourcereferences */
      sourceReferences?: components["schemas"]["WorkbenchV2SourceReferenceView"][];
      /** Sections */
      sections?: components["schemas"]["WorkbenchV2CandidateDetailSectionView"][];
      /** Evidence */
      evidence?: string[];
      /**
       * Detailavailability
       * @enum {string}
       */
      detailAvailability:
        | "available"
        | "redacted"
        | "approval_required"
        | "unavailable";
      /**
       * Accessstate
       * @enum {string}
       */
      accessState: "allowed" | "redacted" | "approval_required" | "denied";
      /**
       * Evidencelevel
       * @enum {string}
       */
      evidenceLevel: "summary" | "detail" | "final" | "unknown";
      /** Reasoncode */
      reasonCode?: string | null;
    };
    /** WorkbenchV2CandidateJobIntentionView */
    WorkbenchV2CandidateJobIntentionView: {
      /** Expectedrole */
      expectedRole?: string | null;
      /** Expectedindustry */
      expectedIndustry?: string | null;
      /** Expectedcity */
      expectedCity?: string | null;
      /** Expectedsalary */
      expectedSalary?: string | null;
    };
    /** WorkbenchV2CandidateMatchView */
    WorkbenchV2CandidateMatchView: {
      /** Summary */
      summary?: string | null;
      /** Strengths */
      strengths?: string[];
      /** Weaknesses */
      weaknesses?: string[];
      /** Score */
      score?: number | null;
      /** Fitbucket */
      fitBucket?: string | null;
    };
    /** WorkbenchV2CandidateSummaryView */
    WorkbenchV2CandidateSummaryView: {
      /** Candidateid */
      candidateId: string;
      /** Rank */
      rank: number;
      /** Displayname */
      displayName: string;
      /** Avatarlabel */
      avatarLabel?: string | null;
      /** Avatarcolorkey */
      avatarColorKey?: string | null;
      /** Headline */
      headline?: string | null;
      /** Company */
      company?: string | null;
      /** Currenttitle */
      currentTitle?: string | null;
      /** Currentcompany */
      currentCompany?: string | null;
      /** Location */
      location?: string | null;
      /** City */
      city?: string | null;
      /** Education */
      education?: string | null;
      /** Experienceyears */
      experienceYears?: number | null;
      /** Workyears */
      workYears?: number | null;
      /** Age */
      age?: number | null;
      /** Gender */
      gender?: string | null;
      /** Activestatus */
      activeStatus?: string | null;
      /** Jobstatus */
      jobStatus?: string | null;
      /** Sourcekinds */
      sourceKinds?: ("cts" | "liepin")[];
      /** Sourcelabel */
      sourceLabel?: string | null;
      /** Matchscore */
      matchScore?: number | null;
      /** Matchsummary */
      matchSummary?: string | null;
      /** Status */
      status: string;
      /**
       * Detailavailability
       * @default unavailable
       * @enum {string}
       */
      detailAvailability:
        | "available"
        | "redacted"
        | "approval_required"
        | "unavailable";
      /**
       * Accessstate
       * @default denied
       * @enum {string}
       */
      accessState: "allowed" | "redacted" | "approval_required" | "denied";
      /**
       * Evidencelevel
       * @default unknown
       * @enum {string}
       */
      evidenceLevel: "summary" | "detail" | "final" | "unknown";
    };
    /** WorkbenchV2CandidateTimelineItemView */
    WorkbenchV2CandidateTimelineItemView: {
      /** Daterange */
      dateRange?: string | null;
      /** Title */
      title?: string | null;
      /** Company */
      company?: string | null;
      /** School */
      school?: string | null;
      /** Major */
      major?: string | null;
      /** Degree */
      degree?: string | null;
      /** Name */
      name?: string | null;
      /** Role */
      role?: string | null;
      /** Description */
      description?: string | null;
    };
    /** WorkbenchV2ConversationEventsView */
    WorkbenchV2ConversationEventsView: {
      /**
       * Schemaversion
       * @default agent.workbench.v2.events
       * @constant
       */
      schemaVersion: "agent.workbench.v2.events";
      /** Conversationid */
      conversationId: string;
      /** Afterstep */
      afterStep: number;
      /** Lateststep */
      latestStep: number;
      /** Events */
      events?: components["schemas"]["WorkbenchV2TranscriptEventView"][];
    };
    /** WorkbenchV2ConversationListSummary */
    WorkbenchV2ConversationListSummary: {
      /** Conversationid */
      conversationId: string;
      /** Title */
      title: string;
      /**
       * Status
       * @enum {string}
       */
      status:
        | "idle"
        | "queued"
        | "running"
        | "completed"
        | "failed"
        | "cancelled";
      /** Updatedat */
      updatedAt: string;
    };
    /** WorkbenchV2ConversationListView */
    WorkbenchV2ConversationListView: {
      /**
       * Schemaversion
       * @default agent.workbench.v2.list
       * @constant
       */
      schemaVersion: "agent.workbench.v2.list";
      /** Conversations */
      conversations?: components["schemas"]["WorkbenchV2ConversationListSummary"][];
    };
    /** WorkbenchV2ConversationPublic */
    WorkbenchV2ConversationPublic: {
      /** Conversationid */
      conversationId: string;
      /** Title */
      title: string;
      /**
       * Runtimestate
       * @default idle
       * @enum {string}
       */
      runtimeState:
        | "idle"
        | "queued"
        | "running"
        | "completed"
        | "failed"
        | "cancelled";
      /** Runtimerunid */
      runtimeRunId?: string | null;
      /** Createdat */
      createdAt: string;
      /** Updatedat */
      updatedAt: string;
    };
    /** WorkbenchV2ConversationView */
    WorkbenchV2ConversationView: {
      /**
       * Schemaversion
       * @default agent.workbench.v2
       * @constant
       */
      schemaVersion: "agent.workbench.v2";
      conversation: components["schemas"]["WorkbenchV2ConversationPublic"];
      /** Transcriptevents */
      transcriptEvents?: components["schemas"]["WorkbenchV2TranscriptEventView"][];
      /** Requirementform */
      requirementForm?: {
        [key: string]: unknown;
      } | null;
      runtime?: components["schemas"]["WorkbenchV2RuntimeView"] | null;
      strategyGraph?: components["schemas"]["WorkbenchV2StrategyGraphView"];
      thinkingProcess?: components["schemas"]["WorkbenchV2ThinkingProcessView"];
      /** Candidates */
      candidates?: components["schemas"]["WorkbenchV2CandidateSummaryView"][];
    };
    /** WorkbenchV2GraphEdgeView */
    WorkbenchV2GraphEdgeView: {
      /** Edgeid */
      edgeId: string;
      /** Fromnodeid */
      fromNodeId: string;
      /** Tonodeid */
      toNodeId: string;
      /** Label */
      label?: string | null;
    };
    /** WorkbenchV2GraphNodeView */
    WorkbenchV2GraphNodeView: {
      /** Nodeid */
      nodeId: string;
      /** Kind */
      kind: string;
      /** Label */
      label: string;
      /** Summary */
      summary?: string | null;
      /** Roundno */
      roundNo?: number | null;
      /** Lanetype */
      laneType?: string | null;
      /** Phase */
      phase?: string | null;
      /** Stage */
      stage?: string | null;
      /**
       * Status
       * @enum {string}
       */
      status:
        | "pending"
        | "running"
        | "completed"
        | "partial"
        | "blocked"
        | "failed"
        | "cancelled";
      /**
       * Sourcekind
       * @default all
       */
      sourceKind: string | null;
      /** Activityid */
      activityId?: string | null;
      /** Messageid */
      messageId?: string | null;
    };
    /** WorkbenchV2MessageRequest */
    WorkbenchV2MessageRequest: {
      /** Message */
      message: string;
      /** Idempotencykey */
      idempotencyKey?: string | null;
    };
    /** WorkbenchV2QueryExecutionView */
    WorkbenchV2QueryExecutionView: {
      /** Sourcekind */
      sourceKind: string;
      /**
       * Status
       * @enum {string}
       */
      status: "completed" | "partial" | "blocked" | "failed";
      /**
       * Rawcandidatecount
       * @default 0
       */
      rawCandidateCount: number;
      /**
       * Uniquecandidatecount
       * @default 0
       */
      uniqueCandidateCount: number;
      /**
       * Duplicatecandidatecount
       * @default 0
       */
      duplicateCandidateCount: number;
      /** Safereasoncode */
      safeReasonCode?: string | null;
    };
    /** WorkbenchV2QueryGroupView */
    WorkbenchV2QueryGroupView: {
      /** Queryinstanceid */
      queryInstanceId: string;
      /** Termgroupkey */
      termGroupKey: string;
      /** Queryrole */
      queryRole: string;
      /** Lanetype */
      laneType: string;
      /** Queryterms */
      queryTerms?: string[];
      /** Keywordquery */
      keywordQuery?: string | null;
      /**
       * Lifecycle
       * @enum {string}
       */
      lifecycle: "planned" | "executed";
      /** Executionstatus */
      executionStatus?: ("completed" | "partial" | "blocked" | "failed") | null;
      /**
       * Attempted
       * @default false
       */
      attempted: boolean;
      /**
       * Rawcandidatecount
       * @default 0
       */
      rawCandidateCount: number;
      /**
       * Uniquecandidatecount
       * @default 0
       */
      uniqueCandidateCount: number;
      /**
       * Duplicatecandidatecount
       * @default 0
       */
      duplicateCandidateCount: number;
      /** Executions */
      executions?: components["schemas"]["WorkbenchV2QueryExecutionView"][];
    };
    /** WorkbenchV2RequirementActionRequest */
    WorkbenchV2RequirementActionRequest: {
      /**
       * Action
       * @enum {string}
       */
      action: "set_selected" | "add_other" | "confirm";
      /** Itemid */
      itemId?: string | null;
      /** Selected */
      selected?: boolean | null;
      /** Text */
      text?: string | null;
      /** Idempotencykey */
      idempotencyKey?: string | null;
    };
    /** WorkbenchV2RuntimeRecheckRequest */
    WorkbenchV2RuntimeRecheckRequest: {
      /** Idempotencykey */
      idempotencyKey: string;
    };
    /** WorkbenchV2RuntimeView */
    WorkbenchV2RuntimeView: {
      /**
       * State
       * @enum {string}
       */
      state:
        | "idle"
        | "queued"
        | "running"
        | "completed"
        | "failed"
        | "cancelled";
      /** Runtimerunid */
      runtimeRunId?: string | null;
    };
    /** WorkbenchV2SourceReferenceView */
    WorkbenchV2SourceReferenceView: {
      /** Sourcekind */
      sourceKind: string;
      /** Displaylabel */
      displayLabel: string;
      /** Url */
      url: string;
    };
    /** WorkbenchV2StrategyGraphView */
    WorkbenchV2StrategyGraphView: {
      /** Nodes */
      nodes?: components["schemas"]["WorkbenchV2GraphNodeView"][];
      /** Edges */
      edges?: components["schemas"]["WorkbenchV2GraphEdgeView"][];
    };
    /** WorkbenchV2ThinkingProcessCardView */
    WorkbenchV2ThinkingProcessCardView: {
      /**
       * Title
       * @enum {string}
       */
      title: "observation" | "反思和下一轮变更";
      /** Text */
      text: string;
      /** Terms */
      terms?: string[];
    };
    /** WorkbenchV2ThinkingProcessRoundView */
    WorkbenchV2ThinkingProcessRoundView: {
      /** Roundno */
      roundNo: number;
      /**
       * Status
       * @enum {string}
       */
      status:
        | "pending"
        | "running"
        | "completed"
        | "partial"
        | "blocked"
        | "failed"
        | "cancelled";
      /** Querygroups */
      queryGroups?: components["schemas"]["WorkbenchV2QueryGroupView"][];
      /** Cards */
      cards?: components["schemas"]["WorkbenchV2ThinkingProcessCardView"][];
    };
    /** WorkbenchV2ThinkingProcessView */
    WorkbenchV2ThinkingProcessView: {
      /** Activeroundno */
      activeRoundNo?: number | null;
      /** Rounds */
      rounds?: components["schemas"]["WorkbenchV2ThinkingProcessRoundView"][];
    };
    /** WorkbenchV2TranscriptEventView */
    WorkbenchV2TranscriptEventView: {
      /** Eventid */
      eventId: string;
      /** Step */
      step: number;
      /**
       * Type
       * @enum {string}
       */
      type:
        | "user_message"
        | "assistant_message"
        | "assistant_status"
        | "requirement_form"
        | "requirement_form_confirmed"
        | "runtime_progress"
        | "runtime_result"
        | "error"
        | "context_summary";
      /**
       * Role
       * @enum {string}
       */
      role: "user" | "assistant" | "system" | "runtime";
      /**
       * Status
       * @enum {string}
       */
      status: "pending" | "running" | "completed" | "failed";
      /** Payload */
      payload?: {
        [key: string]: unknown;
      };
      /** Createdat */
      createdAt: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_conversations_api_agent_workbench_v2_conversations_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkbenchV2ConversationListView"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemDetails"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemDetails"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemDetails"];
        };
      };
    };
  };
  create_conversation_api_agent_workbench_v2_conversations_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorkbenchV2MessageRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkbenchV2ConversationView"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemDetails"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemDetails"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemDetails"];
        };
      };
    };
  };
  get_conversation_api_agent_workbench_v2_conversations__conversation_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkbenchV2ConversationView"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemDetails"];
        };
      };
      /** @description Workbench v2 conversation not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            detail: {
              /** @enum {string} */
              reasonCode: "workbench_v2_conversation_not_found";
            };
          };
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemDetails"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemDetails"];
        };
      };
    };
  };
  list_events_api_agent_workbench_v2_conversations__conversation_id__events_get: {
    parameters: {
      query?: {
        afterStep?: number;
        limit?: number;
      };
      header?: never;
      path: {
        conversation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkbenchV2ConversationEventsView"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemDetails"];
        };
      };
      /** @description Workbench v2 conversation not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            detail: {
              /** @enum {string} */
              reasonCode: "workbench_v2_conversation_not_found";
            };
          };
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemDetails"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemDetails"];
        };
      };
    };
  };
  get_candidate_detail_api_agent_workbench_v2_conversations__conversation_id__candidates__candidate_id__detail_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversation_id: string;
        candidate_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkbenchV2CandidateDetailView"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemDetails"];
        };
      };
      /** @description Workbench v2 conversation not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            detail: {
              /** @enum {string} */
              reasonCode: "workbench_v2_conversation_not_found";
            };
          };
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemDetails"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemDetails"];
        };
      };
    };
  };
  submit_message_api_agent_workbench_v2_conversations__conversation_id__messages_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorkbenchV2MessageRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkbenchV2ConversationView"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemDetails"];
        };
      };
      /** @description Workbench v2 conversation not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            detail: {
              /** @enum {string} */
              reasonCode: "workbench_v2_conversation_not_found";
            };
          };
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemDetails"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemDetails"];
        };
      };
    };
  };
  apply_requirement_action_api_agent_workbench_v2_conversations__conversation_id__requirement_actions_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorkbenchV2RequirementActionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkbenchV2ConversationView"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemDetails"];
        };
      };
      /** @description Workbench v2 conversation not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            detail: {
              /** @enum {string} */
              reasonCode: "workbench_v2_conversation_not_found";
            };
          };
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemDetails"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemDetails"];
        };
      };
    };
  };
  recheck_and_continue_api_agent_workbench_v2_conversations__conversation_id__runtime_recheck_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorkbenchV2RuntimeRecheckRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkbenchV2ConversationView"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemDetails"];
        };
      };
      /** @description Workbench v2 conversation not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            detail: {
              /** @enum {string} */
              reasonCode: "workbench_v2_conversation_not_found";
            };
          };
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemDetails"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemDetails"];
        };
      };
    };
  };
  create_compliance_gate_api_liepin_compliance_gates_post: {
    parameters: {
      query?: never;
      header?: {
        "X-SeekTalent-API-Key"?: string | null;
        "X-Tenant-ID"?: string | null;
        "X-Workspace-ID"?: string | null;
        "X-Actor-ID"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LiepinComplianceGateCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LiepinComplianceGateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_compliance_gate_api_liepin_compliance_gates__gate_ref__get: {
    parameters: {
      query?: never;
      header?: {
        "X-SeekTalent-API-Key"?: string | null;
        "X-Tenant-ID"?: string | null;
        "X-Workspace-ID"?: string | null;
        "X-Actor-ID"?: string | null;
      };
      path: {
        gate_ref: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LiepinComplianceGateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  bind_compliance_gate_account_api_liepin_compliance_gates__gate_ref__bind_account_post: {
    parameters: {
      query?: never;
      header?: {
        "X-SeekTalent-API-Key"?: string | null;
        "X-Tenant-ID"?: string | null;
        "X-Workspace-ID"?: string | null;
        "X-Actor-ID"?: string | null;
      };
      path: {
        gate_ref: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LiepinComplianceGateConnectionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LiepinComplianceGateActionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  verify_compliance_gate_api_liepin_compliance_gates__gate_ref__verify_post: {
    parameters: {
      query?: never;
      header?: {
        "X-SeekTalent-API-Key"?: string | null;
        "X-Tenant-ID"?: string | null;
        "X-Workspace-ID"?: string | null;
        "X-Actor-ID"?: string | null;
      };
      path: {
        gate_ref: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LiepinComplianceGateConnectionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LiepinComplianceGateActionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_connection_api_liepin_connections_post: {
    parameters: {
      query?: never;
      header?: {
        "X-SeekTalent-API-Key"?: string | null;
        "X-Tenant-ID"?: string | null;
        "X-Workspace-ID"?: string | null;
        "X-Actor-ID"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LiepinConnectionCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LiepinConnectionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_connection_api_liepin_connections__connection_id__get: {
    parameters: {
      query?: never;
      header?: {
        "X-SeekTalent-API-Key"?: string | null;
        "X-Tenant-ID"?: string | null;
        "X-Workspace-ID"?: string | null;
        "X-Actor-ID"?: string | null;
      };
      path: {
        connection_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LiepinConnectionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_login_url_api_liepin_connections__connection_id__login_url_post: {
    parameters: {
      query?: never;
      header?: {
        "X-SeekTalent-API-Key"?: string | null;
        "X-Tenant-ID"?: string | null;
        "X-Workspace-ID"?: string | null;
        "X-Actor-ID"?: string | null;
      };
      path: {
        connection_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LiepinLoginUrlResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_connection_stream_token_api_liepin_connections__connection_id__stream_token_post: {
    parameters: {
      query?: never;
      header?: {
        "X-SeekTalent-API-Key"?: string | null;
        "X-Tenant-ID"?: string | null;
        "X-Workspace-ID"?: string | null;
        "X-Actor-ID"?: string | null;
      };
      path: {
        connection_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  stream_connection_events_api_liepin_connections__connection_id__events_get: {
    parameters: {
      query?: never;
      header?: {
        "Last-Event-ID"?: string | null;
      };
      path: {
        connection_id: string;
      };
      cookie?: {
        liepin_stream_token?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
