from __future__ import annotations


LIEPIN_WORKER_SAFE_REASON_CODES = frozenset(
    {
        "liepin_opencli_backend_disabled",
        "liepin_opencli_command_missing",
        "liepin_opencli_extension_disconnected",
        "liepin_opencli_daemon_not_running",
        "liepin_opencli_daemon_stale",
        "liepin_opencli_status_unavailable",
        "liepin_opencli_bootstrap_failed",
        "liepin_opencli_forbidden_command",
        "liepin_opencli_forbidden_text",
        "liepin_opencli_host_blocked",
        "liepin_opencli_start_url_blocked",
        "liepin_opencli_window_policy_blocked",
        "liepin_opencli_budget_exhausted",
        "liepin_opencli_timeout",
        "liepin_opencli_detail_not_opened",
        "liepin_opencli_detail_open_retry_exhausted",
        "liepin_opencli_login_required",
        "liepin_opencli_identity_intercept",
        "liepin_opencli_risk_page",
        "liepin_opencli_unknown_modal",
        "liepin_opencli_source_policy_missing",
        "liepin_opencli_config_invalid",
        "liepin_opencli_removed_config",
        "liepin_opencli_helper_empty_output",
        "liepin_opencli_helper_invalid_input",
        "liepin_opencli_helper_invalid_output",
        "liepin_opencli_helper_output_too_large",
        "liepin_opencli_malformed_state",
        "liepin_opencli_lease_malformed",
        "liepin_opencli_owned_marker_malformed",
        "liepin_opencli_tab_response_malformed",
        "liepin_opencli_filter_unapplied",
        "liepin_opencli_search_input_unapplied",
        "liepin_opencli_search_not_ready",
        "liepin_opencli_results_not_ready",
        "liepin_opencli_stale_ref",
        "liepin_opencli_selector_not_found",
        "liepin_opencli_selector_ambiguous",
        "liepin_opencli_target_not_found",
    }
)

LIEPIN_PUBLIC_EVENT_REASON_MAP = {
    "liepin_connection_not_connected": "source_login_required",
    "liepin_browser_login_required": "source_login_required",
    "liepin_browser_probe_unavailable": "source_browser_backend_unavailable",
    "liepin_browser_account_mismatch": "source_account_mismatch",
    "liepin_opencli_backend_disabled": "source_browser_backend_unavailable",
    "liepin_opencli_command_missing": "source_browser_backend_unavailable",
    "liepin_opencli_extension_disconnected": "source_browser_extension_disconnected",
    "liepin_opencli_daemon_not_running": "source_browser_backend_unavailable",
    "liepin_opencli_daemon_stale": "source_browser_backend_unavailable",
    "liepin_opencli_status_unavailable": "source_browser_backend_unavailable",
    "liepin_opencli_bootstrap_failed": "source_browser_backend_unavailable",
    "liepin_opencli_forbidden_command": "source_browser_policy_blocked",
    "liepin_opencli_forbidden_text": "source_browser_policy_blocked",
    "liepin_opencli_host_blocked": "source_browser_policy_blocked",
    "liepin_opencli_start_url_blocked": "source_browser_policy_blocked",
    "liepin_opencli_window_policy_blocked": "source_browser_policy_blocked",
    "liepin_opencli_budget_exhausted": "source_budget_exhausted",
    "liepin_opencli_timeout": "source_browser_timeout",
    "liepin_opencli_login_required": "source_login_required",
    "liepin_opencli_identity_intercept": "source_risk_or_verification_required",
    "liepin_opencli_risk_page": "source_risk_or_verification_required",
    "liepin_opencli_unknown_modal": "source_browser_interaction_required",
    "liepin_opencli_source_policy_missing": "source_browser_policy_blocked",
    "liepin_opencli_config_invalid": "source_browser_backend_unavailable",
    "liepin_opencli_removed_config": "source_browser_backend_unavailable",
    "liepin_opencli_helper_empty_output": "source_browser_backend_unavailable",
    "liepin_opencli_helper_invalid_input": "source_browser_backend_unavailable",
    "liepin_opencli_helper_invalid_output": "source_browser_backend_unavailable",
    "liepin_opencli_helper_output_too_large": "source_browser_backend_unavailable",
    "liepin_opencli_malformed_state": "source_browser_backend_unavailable",
    "liepin_opencli_lease_malformed": "source_browser_backend_unavailable",
    "liepin_opencli_owned_marker_malformed": "source_browser_backend_unavailable",
    "liepin_opencli_tab_response_malformed": "source_browser_backend_unavailable",
    "liepin_opencli_detail_not_opened": "source_browser_timeout",
    "liepin_opencli_detail_open_retry_exhausted": "source_browser_timeout",
    "liepin_opencli_filter_unapplied": "source_filter_unavailable",
    "liepin_opencli_search_input_unapplied": "source_browser_backend_unavailable",
    "liepin_opencli_search_not_ready": "source_browser_backend_unavailable",
    "liepin_opencli_results_not_ready": "source_browser_backend_unavailable",
    "liepin_opencli_stale_ref": "source_browser_backend_unavailable",
    "liepin_opencli_selector_not_found": "source_browser_backend_unavailable",
    "liepin_opencli_selector_ambiguous": "source_browser_backend_unavailable",
    "liepin_opencli_target_not_found": "source_browser_backend_unavailable",
}

LIEPIN_SOURCE_LANE_REASON_CODE_MAP = {
    "liepin_opencli_backend_disabled": "source_browser_backend_unavailable",
    "liepin_opencli_command_missing": "source_browser_backend_unavailable",
    "liepin_opencli_extension_disconnected": "source_browser_backend_unavailable",
    "liepin_opencli_daemon_not_running": "source_browser_backend_unavailable",
    "liepin_opencli_daemon_stale": "source_browser_backend_unavailable",
    "liepin_opencli_status_unavailable": "source_browser_backend_unavailable",
    "liepin_opencli_bootstrap_failed": "source_browser_backend_unavailable",
    "liepin_opencli_forbidden_command": "source_browser_backend_unavailable",
    "liepin_opencli_forbidden_text": "source_browser_backend_unavailable",
    "liepin_opencli_host_blocked": "source_browser_backend_unavailable",
    "liepin_opencli_start_url_blocked": "source_browser_backend_unavailable",
    "liepin_opencli_window_policy_blocked": "source_browser_backend_unavailable",
    "liepin_opencli_budget_exhausted": "blocked_budget_exhausted",
    "liepin_opencli_timeout": "source_browser_timeout",
    "liepin_opencli_login_required": "source_login_required",
    "liepin_opencli_identity_intercept": "source_login_required",
    "liepin_opencli_risk_page": "source_risk_challenge",
    "liepin_opencli_unknown_modal": "source_risk_challenge",
    "liepin_opencli_source_policy_missing": "source_browser_backend_unavailable",
    "liepin_opencli_config_invalid": "source_browser_backend_unavailable",
    "liepin_opencli_removed_config": "source_browser_backend_unavailable",
    "liepin_opencli_helper_empty_output": "source_browser_backend_unavailable",
    "liepin_opencli_helper_invalid_input": "source_browser_backend_unavailable",
    "liepin_opencli_helper_invalid_output": "source_browser_backend_unavailable",
    "liepin_opencli_helper_output_too_large": "source_browser_backend_unavailable",
    "liepin_opencli_malformed_state": "source_browser_backend_unavailable",
    "liepin_opencli_lease_malformed": "source_browser_backend_unavailable",
    "liepin_opencli_owned_marker_malformed": "source_browser_backend_unavailable",
    "liepin_opencli_tab_response_malformed": "source_browser_backend_unavailable",
    "liepin_opencli_detail_not_opened": "source_browser_timeout",
    "liepin_opencli_detail_open_retry_exhausted": "source_browser_timeout",
    "liepin_opencli_filter_unapplied": "source_filter_unavailable",
    "liepin_opencli_search_input_unapplied": "source_browser_backend_unavailable",
    "liepin_opencli_search_not_ready": "source_browser_backend_unavailable",
    "liepin_opencli_results_not_ready": "source_browser_backend_unavailable",
    "liepin_opencli_stale_ref": "source_browser_backend_unavailable",
    "liepin_opencli_selector_not_found": "source_browser_backend_unavailable",
    "liepin_opencli_selector_ambiguous": "source_browser_backend_unavailable",
    "liepin_opencli_target_not_found": "source_browser_backend_unavailable",
}

LIEPIN_SOURCE_LANE_SAFE_REASON_CODES = LIEPIN_WORKER_SAFE_REASON_CODES

LIEPIN_BACKEND_MODE_BY_WORKER_MODE = {
    "disabled": "blocked",
    "opencli": "opencli",
    "fake_fixture": "fake_fixture",
}
