"""One-to-one #322 section 6 field coverage for diagnostics v1 artifacts."""

MACHINE_CAPABILITY_FIELD_COVERAGE = {
    "identity_revision_time": ("receipt_id", "revision", "generated_at"),
    "canonical_created_observed": ("canonical_hash", "created_at", "observed_at"),
    "release_product_domi": (
        "release_manifest_ref",
        "product_version",
        "product_build_ref",
        "domi_version",
        "domi_build_ref",
        "install_channel",
    ),
    "os_arch_runtime": (
        "platform",
        "architecture",
        "os_family",
        "os_build",
        "os_version_bucket",
        "runtime_versions",
        "chrome_channel",
    ),
    "slot_switch_rollback": (
        "active_slot_ref",
        "previous_slot_ref",
        "switch_status",
        "rollback_status",
    ),
    "artifact_signature": (
        "manifest_hash",
        "artifact_hash",
        "manifest_signature_status",
        "artifact_signature_status",
    ),
    "bridge_component": (
        "component_build_refs",
        "bridge_implementation",
        "bridge_build_ref",
        "bridge_protocol_ref",
        "bridge_capabilities",
    ),
    "profile_extension_account": (
        "profile_mode",
        "profile_binding_hash",
        "profile_binding_generation",
        "extension_version",
        "extension_id_hash",
        "provider_account_hash",
    ),
    "endpoint_database_disk_network": (
        "endpoint_ownership",
        "database_logical_name",
        "database_schema_version",
        "database_journal_mode",
        "database_integrity",
        "database_file_size_bucket",
        "database_wal_size_bucket",
        "database_shm_size_bucket",
        "disk_free_size_bucket",
        "disk_writable",
        "disk_executable",
        "network_posture",
    ),
    "result_gaps": ("capabilities", "result", "gap_codes"),
}

STARTUP_RECEIPT_FIELD_COVERAGE = {
    "identity_revision_time": (
        "startup_receipt_id",
        "revision",
        "canonical_hash",
        "created_at",
        "observed_at",
    ),
    "component_parent_release": (
        "component",
        "component_instance_id",
        "parent_instance_id",
        "capability_receipt_ref",
        "release_manifest_ref",
        "component_build_ref",
    ),
    "protocol_capability": ("protocol_refs", "capability_refs"),
    "startup_readiness_exit": (
        "startup_kind",
        "started_at",
        "readiness_observed_at",
        "exited_at",
        "readiness",
        "reason_code",
        "restart_count",
        "restart_budget_ref",
        "previous_instance_ref",
        "last_exit_cause_ref",
    ),
    "profile_browser_extension_worker": (
        "profile_binding_generation",
        "browser_control_scope_id",
        "extension_install_generation",
        "service_worker_generation",
    ),
    "database_endpoint": ("database_refs", "endpoint_ownership_ref"),
}

OPERATION_EVIDENCE_FIELD_COVERAGE = {
    "identity_revision": ("operation_evidence_id", "revision"),
    "canonical_created_observed_release": (
        "canonical_hash",
        "created_at",
        "observed_at",
        "release_manifest_ref",
    ),
    "identity_authority": (
        "correlation_id",
        "run_id",
        "operation_id",
        "attempt_no",
        "diagnostic_trace_id",
        "authority_refs",
    ),
    "receipt_event_failure_refs": (
        "capability_receipt_refs",
        "startup_receipt_refs",
        "first_event_ref",
        "last_event_ref",
        "failure_envelope_ref",
        "checkpoint_ref",
    ),
    "operation_boundaries_outcome": (
        "source_id",
        "operation_kind",
        "boundary_facts",
        "summary",
        "source_operation_disposition_ref",
        "source_operation_disposition",
        "product_outcome_ref",
        "product_outcome",
        "missing_evidence_refs",
        "rejected_stale_write_count",
        "journal_truncation",
    ),
}
