#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export SEEKTALENT_DEV_BACKEND_HOST="${SEEKTALENT_DEV_BACKEND_HOST:-192.168.203.39}"
export SEEKTALENT_DEV_BACKEND_PORT="${SEEKTALENT_DEV_BACKEND_PORT:-8022}"
export SEEKTALENT_DEV_FRONTEND_HOST="${SEEKTALENT_DEV_FRONTEND_HOST:-192.168.203.39}"
export SEEKTALENT_DEV_FRONTEND_PORT="${SEEKTALENT_DEV_FRONTEND_PORT:-5179}"
export SEEKTALENT_UI_LAN="${SEEKTALENT_UI_LAN:-1}"
export SEEKTALENT_WORKSPACE_ROOT="${SEEKTALENT_WORKSPACE_ROOT:-$ROOT/.lan-workspace}"
export SEEKTALENT_CODE_ROOT="${SEEKTALENT_CODE_ROOT:-$ROOT}"
export SEEKTALENT_LIEPIN_OPENCLI_SESSION="${SEEKTALENT_LIEPIN_OPENCLI_SESSION:-seektalent-liepin-lan}"

exec "$ROOT/scripts/start-dev-workbench.sh"
